### ISSUE TITLE
グローバルホットキー対応

### ISSUE THREAD

**Issue by guredora403** [actlaboratory/LAMP#43]
曲の再生停止や次の曲、前の曲などの操作はグローバルホットキーにするとよいと思います。なにげにグローバルホットキーが使えるメディアプレイヤーをあまり知りません。

**Comment by guredora403** [comment]
ホットキーなのでよくキーボードの上のほうについているマルチメディアキーにも対応してください。おそらく専用のキーコードがあるはずです。

**Comment by yamahubuki** [comment]
こちらにそれがついたキーボードがないため検証できていませんが、対応済みという認識です。

デバイスをお持ちであればb動作確認をお願いします。hotkeyブランチで現在作業中です。
