### ISSUE TITLE
ショートカットキー設定とグローバルホットキー設定の違いが分からない

### ISSUE THREAD

**Issue by yncat** [actlaboratory/LAMP#56]
グローバルホットキー設定を開くと、ウィンドウタイトルが「ショートカットキー設定」となっている。
微妙に中の項目が違うようだが、それぞれなにをするものなのかが分からない。

**Comment by yamahubuki** [comment]
@hrk-fujii
この件はTCVにて指摘されており、対応済みです。
関連するファイルをTCVからコピーして上書きし、views/Mainからの呼び出し時のInitializeにてタイトル指定してください。
