### ISSUE TITLE
スライドバーとアクセラレータのキー重複

### ISSUE THREAD

**Issue by hrk-fujii** [actlaboratory/LAMP#9]
スライドバーにフォーカスがある状態でアクセラレータのキー操作（ctrl+上下）を行うと、バーの値が意図せず変更されてしまう。

**Comment by yamahubuki** [comment]
Slider.SetLineSize(0)
で解決しそうです。

上下矢印キーでの移動幅を設定する関数なので、上下キーでの移動の無効化はこれでできると思われます。
